### ISSUE TITLE
Cannot modify data of list entry. Was this meant to be this way?

### ISSUE THREAD

**Issue by TheStefan** [fragglet/c-algorithms#11]
There are functions to get the value of a ListEntry, but there are no functions to write to the data of a ListEntry.

The underlying struct is defined in the list.c file so it is not possible to access it directly.

I am willing to implement the feature if needed.

**Comment by fragglet** [comment]
Good point. I think there should probably be a way to set the data like you say (and for slist too).

I think it was an oversight on my part when I first wrote it; I usually think of linked lists as an immutable data structure, or at least one that should be used in an immutable way. But this is C and not Lisp after all.

There should probably be similar functions for setting the 'next' pointer (unless necessary, not for 'prev' though).

**Comment by TheStefan** [comment]
Im not sure if you shoukd be able to modify the next pointer. At least for the double linked list, since it would not be clear what to do with the prev pointer of the new next entry. If we do not set the prev option it would render a corrupt double linked list since it the path backwards ends up in other entries than in the path forward. If we set prev we also imply that we get rid of a piece of list which might not be intended by the user.

For a single linked list we would have the problem that you can easily remove a sublist from the list.

The set data mehtods will be committed.
