### ISSUE TITLE
Build on Mac

### ISSUE THREAD

**Issue by GoingMyWay** [fragglet/c-algorithms#18]
On Mac how can I build the code, I found `autogen.sh` can't run on Mac.

**Comment by fragglet** [comment]
Please download c-algorithms-1.2.0.tar.gz from the releases page and follow the instructions in INSTALL.

**Comment by hnspn** [comment]
> On Mac how can I build the code, I found `autogen.sh` can't run on Mac.

Had the same problem.
The autogen.sh error message for me was
`libtoolize command not found`
So I installed glibtool and ran it manually.
After that autogen worked and the make too.
