### ISSUE TITLE
[bug] rb-tree: Calling the comparator on node values instead of keys

### ISSUE THREAD

**Issue by donaldong** [fragglet/c-algorithms#29]
https://github.com/fragglet/c-algorithms/blob/17cd712ef84948ce5c3faae911bc797ebad26e09/src/rb-tree.c#L377

This line should check the keys, not the values.

Separately, does this repro accept new features such as implementing the missing deletion functionality in rbtree?

Thanks!

**Comment by fragglet** [comment]
Fixed today, thanks for the report and apologies for belated response
