### ISSUE TITLE
Do we need to call `arraylist_new` again in a cleared array list when we want to put items.

### ISSUE THREAD

**Issue by kcvinker** [fragglet/c-algorithms#39]
Hi,
I am using the arraylist library in cython hobby project. So far so good. My project is a win32 api ui library. I have list box control . It has an `items` property which is internally your arraylist. I need to implement an option to clear all the items from list box. It's okay, because I can call the `arraylist_clear` function. But after clearing the arraylist, if my user wants to put another set of items what should I do ? Should I call `arraylist_free` & `arraylist_new` ? 
Thanks in advance.

**Comment by fragglet** [comment]
There is no need to do that.

**Comment by kcvinker** [comment]
Thanks!
